### ISSUE TITLE
Bootstrap should create secret for git token and configure repositoryCredentials

### ISSUE THREAD

**Issue by haf-tech** [redhat-developer/kam#130]
**Describe the bug**
In case a private Git repo is with the `kam bootstrap` command used and the flag `--git-host-access-token` is set, does the first sync of the ArgoCD Apps not work, as long no credentials and a proper ArgoCD configuration exist.

**To Reproduce**

1. Bootstrap
```
kam_darwin_amd64 bootstrap \
  --service-repo-url https://github.com/k8s-universe/tekton-101 \
  --gitops-repo-url https://github.com/k8s-universe/tekton-101-kam-gitops.git \
  --image-repo demo-tekton-kam-gitops/tekton-101 \
  --git-host-access-token 8234d.... \
  --output . \
  --push-to-git=false \
  --sealed-secrets-ns=cicd \
  --sealed-secrets-svc=sealedsecretcontroller-sealed-secrets
```
2. Git push
3. `oc apply -k config/argocd`
4. wait and check the result in ArgoCD UI...sync does not work. Error message `authentication needed`

**Expected behavior**
The generated `ArgoCD` resource definition should contains the `repositories` part with a reference to a secret, which should also be created containing the git PAT

Example
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  creationTimestamp: null
  name: argocd
  namespace: argocd
spec:
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  dex:
    image: quay.io/redhat-cop/dex
    openShiftOAuth: true
    version: v2.22.0-openshift
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  server:
    route:
      enabled: true
  repositoryCredentials: |
    - url: https://github.com/k8s-universe/tekton-101-kam-gitops.git
      passwordSecret:
        name: argocd-demo-kam-tekton101
        key: password
      usernameSecret:
        name: argocd-demo-kam-tekton101
        key: username
    - url: https://github.com/k8s-universe/tekton-101.git
      passwordSecret:
        name: argocd-demo-kam-tekton101
        key: password
      usernameSecret:
        name: argocd-demo-kam-tekton101
        key: username
```

**Screenshots**
n/a

**Additional context**
Possible workaround, til in `kam bootstrap` ;-) Update docu
Commands to create the Secrets via `kubeseal` . Important set the correct value for `SealedSecret` `namespace`, `controller-name` and general `namespace` 

```
$ echo -n "token" | kubectl create secret generic argocd-demo-kam-tekton101 --dry-run=true --from-file=username=/dev/stdin -o json | kubeseal -n argocd --controller-name=sealedsecretcontroller-sealed-secrets --controller-namespace=cicd > argocd-demo-kam-tekton101.json

$ echo -n "8234d...." | kubectl create secret generic argocd-demo-kam-tekton101 --dry-run=true --from-file=password=/dev/stdin -o json | kubeseal -n argocd --controller-name=sealedsecretcontroller-sealed-secrets --controller-namespace=cicd --merge-into argocd-demo-kam-tekton101.json

$ oc apply -f argocd-demo-kam-tekton101.json
sealedsecret.bitnami.com/argocd-demo-kam-tekton101 created
```
